### ISSUE TITLE
Not working correctly on 22623.730

### ISSUE THREAD

**Issue by XPower7125** [FireCubeStudios/FluentFlyouts3#1] opened 2022-10-10 10:19 UTC
![image](https://user-images.githubusercontent.com/64551044/194844698-5351f2d0-60f1-4e81-b2c7-5aae8bb6cce4.png)
I have the new systray + tablet optimized taskbar but I don't think this is the problem

**Comment by FireCubeStudios** [comment] 2022-10-10 10:40
Duplicate of #2

**Closed** 2022-10-10 11:43 UTC
